### ISSUE TITLE
Review: Chris P.: nits

### ISSUE THREAD

**Issue by cjpatton** [divergentdave/draft-dcook-ppm-dap-interop-test-design#15]
- [ ] The reference to the DAP draft is "DAP-PPM", but elsewhere (cf. VDAF draft) we're using simply "DAP". We should align the reference we use. Do you have strong preference for DAP-PPM?
- [ ] The markdown for most I-Ds I've seen wrap lines at 80 characters. This is totally up to you, of course! One reason to do this is that it makes reviewing PRs easier.

**Comment by divergentdave** [comment]
I don't have a strong preference for DAP or DAP-PPM, I used DAP-PPM initially because it was in the `abbrev` key of the metadata.

I'll wrap lines once I close out my outstanding PRs.
