### ISSUE TITLE
Review: ChrisP.: s.4.3.2: Why pass "aggregatorId" with task config?

### ISSUE THREAD

**Issue by cjpatton** [divergentdave/draft-dcook-ppm-dap-interop-test-design#19]
Presumably the server is configured to be either the helper or leader but not both.

**Comment by divergentdave** [comment]
The intent of this parameter is to allow dropping a single aggregator implementation into either role, if it supports both. See [section 3](https://divergentdave.github.io/draft-dcook-ppm-dap-interop-test-design/draft-dcook-ppm-dap-interop-test-design.html#section-3-1):

> Implementations may want to submit a single aggregator image in both the leader list and helper list.

Having this parameter means we can configure such aggregators at run time, at the same time we supply the rest of the task parameters.

**Comment by cjpatton** [comment]
Ohh, that makes a lot of sense. Good idea.

How about instead of

>  0 if this aggregator is the leader, or 1 if this aggregator is the helper.

we align the ID with `enum Role` in the DAP spec?
