### ISSUE TITLE
Reconsider API design for authentication

### ISSUE THREAD

**Issue by divergentdave** [divergentdave/draft-dcook-ppm-dap-interop-test-design#28]
In the discussion on https://github.com/divviup/janus/pull/654#discussion_r1001991053, we're considering eliminating `/internal/test/add_authentication_token` API, and folding authentication-related information into a sub-object in the `/internal/test/add_task` request.

This would go in the opposite direction as #17. Would it be acceptable to keep the authentication parameters rolled in with task configuration for the time being, and revisit decoupling authentication in future versions once things have matured further? Chris, would this pose any implementation issues with Daphne?

cc @branlwyd @cjpatton

**Comment by cjpatton** [comment]
This is very doable. Go ahead and stick the auth tokesn back into the add task endpoint. 🚢

**Comment by divergentdave** [comment]
I opened #29 for this
