### ISSUE TITLE
`draft-ietf-ppm-dap-09` updates

### ISSUE THREAD

**Issue by tgeoghegan** [divergentdave/draft-dcook-ppm-dap-interop-test-design#43]
We need a draft to catch up with the latest DAP. The measurement type for `Prio3Count` has changed from `u64` to `bool` and this should be reflected in this draft. There may be other changes needed.

**Comment by divergentdave** [comment]
FWIW, the VDAF specification itself hasn't changed, it still says the measurement type is "Unsigned, in range [0, 2)".

**Comment by branlwyd** [comment]
The measurement type for `Prio3Count` in [VDAF-08](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-08.html#name-prio3count) is still "Unsigned, in range `[0,2)`". `libprio-rs` made an implementation choice to represent this as a `bool`; I'm not sure it's appropriate to extend this to the specs, which are likely easier to phrase if all of the `Prio3` constructions use numeric values (though I'll let the VDAF editors weigh in on this).

**Comment by tgeoghegan** [comment]
Ah, I forgotten or not noticed that libprio-rs disagrees with the specs here. In that case, we should probably do nothing here, since this draft is not specifically for testing libprio-rs.

**Comment by tgeoghegan** [comment]
Closing since I don't think there's anything to do here.
